import Head from 'next/head';
import { Input } from 'packages.inputs.input';
import { useState } from 'react';

export default function Home() {
  const [value, setValue] = useState('');
  return (
    <div>
      <Head>
        <title>Powerful</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Powerful</p>
      <Input value={value} onChange={(e) => setValue(e.target.value)} />
    </div>
  );
}
